// Approach foundation (Humanist Minimal): builds the illustration library, motion
// CSS and example SVGs. Runs after the colour foundation, whose tokens give the palettes.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createIllustrator } from './illustration.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

/** Illustration palette for a combination's roles: ground and accent from Wada, ink Black, paper White. */
export function illustrationPalette(roles, byHex) {
  return { ground: byHex(roles.bg), accent: byHex(roles.accent), ink: byHex('black'), paper: byHex('white') };
}

export function buildApproach({ dist }) {
  const write = (p, data) => {
    const full = join(dist, p);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, data);
  };
  const approach = JSON.parse(readFileSync(join(HERE, 'source/approach.json'), 'utf8'));
  const color = JSON.parse(readFileSync(join(dist, 'tokens/colors.json'), 'utf8'));
  const hexOf = Object.fromEntries(color.colors.map((c) => [c.id, c.hex]));
  const hex = (id) => hexOf[id];

  const brand = color.brand.find((b) => b.name === 'primary') || color.brand[0];
  const palettes = Object.fromEntries(color.brand.map((b) => [b.name, illustrationPalette(b.roles, hex)]));
  const primary = brand ? palettes[brand.name] : { ground: hex('white'), accent: hex('black'), ink: hex('black'), paper: hex('white') };

  const ill = createIllustrator(approach, primary);
  const M = approach.motion;
  const banner = '/* UnDesigned Humanist Minimal. Generated by foundations/approach/build.mjs; do not edit by hand. */\n';

  // tokens
  write('tokens/approach.json', JSON.stringify({ ...approach, $comment: undefined, palettes }, null, 2) + '\n');

  // web: illustration library with the approach data and brand palettes built in
  const lib = readFileSync(join(HERE, 'illustration.mjs'), 'utf8').replace(/^export /gm, '');
  const combos = Object.fromEntries(color.combinations.map((c) => [c.id, { light: c.roles.light, dark: c.roles.dark }]));
  write(
    'web/js/illustration.mjs',
    `${banner}${lib}
const approach = ${JSON.stringify(approach)};
const palettes = ${JSON.stringify(palettes)};
const hexOf = ${JSON.stringify(hexOf)};
const combos = ${JSON.stringify(combos)};
/** Illustration palette for any Wada combination (1-348). */
function paletteFor(n, mode = 'light') {
  const r = combos[n] && combos[n][mode === 'dark' ? 'dark' : 'light'];
  if (!r) throw new Error('Unknown combination ' + n);
  return { ground: hexOf[r.bg], accent: hexOf[r.accent], ink: hexOf.black, paper: hexOf.white };
}
const illustrator = createIllustrator(approach, palettes.primary || Object.values(palettes)[0]);
/** scene({ motif, palette, animate }) -> SVG string. motifs: ${ill.motifs.join(', ')} */
const scene = illustrator.scene;
export { approach, palettes, paletteFor, illustrator, scene, createIllustrator };
`,
  );

  // web: motion tokens and classes for any HTML element
  let css = `${banner}
:root {
  --ud-motion-draw: ${M.draw.duration}ms;
  --ud-motion-pop: ${M.pop.duration}ms;
  --ud-motion-morph: ${M.morph.duration}ms;
  --ud-motion-radiate: ${M.radiate.duration}ms;
  --ud-motion-loop: ${M.loop}ms;
  --ud-motion-stagger: ${M.stagger}ms;
  --ud-motion-hold: ${M.hold}ms;
  --ud-ease-draw: ${M.draw.easing};
  --ud-ease-pop: ${M.pop.easing};
  --ud-ease-morph: ${M.morph.easing};
}

/* Line draws itself on. Put pathLength="1" on the SVG path. */
.ud-draw { stroke-dasharray: 1; stroke-dashoffset: 1; animation: ud-draw var(--ud-motion-draw) var(--ud-ease-draw) both; }
@keyframes ud-draw { to { stroke-dashoffset: 0; } }

/* Shape or element pops in with a small overshoot. */
.ud-pop { transform-box: fill-box; transform-origin: center; animation: ud-pop var(--ud-motion-pop) var(--ud-ease-pop) both; }
@keyframes ud-pop { from { transform: scale(0); } to { transform: scale(1); } }

/* Text or block rises in (for headlines next to an illustration). */
.ud-rise { animation: ud-rise var(--ud-motion-morph) var(--ud-ease-morph) both; }
@keyframes ud-rise { from { transform: translateY(0.4em); opacity: 0; } to { transform: none; opacity: 1; } }

/* Stagger children: style="--i: 0", "--i: 1" ... */
.ud-stagger > * { animation-delay: calc(var(--i, 0) * var(--ud-motion-stagger)); }

@media (prefers-reduced-motion: reduce) {
  .ud-draw, .ud-pop, .ud-rise { animation: none; stroke-dashoffset: 0; }
}
`;
  write('web/css/motion.css', css);

  // example SVGs in the primary brand palette
  for (const motif of ill.motifs) {
    write(`illustration/svg/${motif}.svg`, ill.scene({ motif, animate: false, uid: motif.replace(/-/g, '') }) + '\n');
    write(`illustration/svg/${motif}-animated.svg`, ill.scene({ motif, animate: true, uid: motif.replace(/-/g, '') }) + '\n');
  }

  return [
    `approach: ${approach.name}, ${approach.principles.length} principles, ${approach.layers.length} layer rules, ${ill.motifs.length} illustration motifs`,
    `  illustrations use brand palette "${brand ? brand.name : 'none'}" (combination ${brand ? brand.combination : '-'})`,
  ];
}
