// Typography foundation: builds a brand's type CSS, tokens and font list from
// its chosen pairing (brand.json -> typography) and source/pairings.json.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

export function loadPairings() {
  return JSON.parse(readFileSync(join(HERE, 'source/pairings.json'), 'utf8'));
}

export function loadHandwritten() {
  return JSON.parse(readFileSync(join(HERE, 'source/handwritten.json'), 'utf8'));
}

/** The product's handwritten accent face, checked against its style's rules (or null). */
export function handFace(brand) {
  const id = (brand.config.typography || {}).hand;
  if (!id) return null;
  const lib = loadHandwritten();
  const face = lib.fonts.find((f) => f.id === id);
  if (!face) throw new Error(`${brand.id}/brand.json: unknown hand face "${id}". Available: ${lib.fonts.map((f) => f.id).join(', ')}`);
  const approach = brand.config.approach;
  const ty = JSON.parse(readFileSync(join(HERE, '../../approaches', approach, 'typography.json'), 'utf8'));
  const rule = ty.handwritten || { use: 'none', fonts: [] };
  if (rule.use === 'none') throw new Error(`${brand.id}/brand.json: the ${approach} style does not use handwritten faces (${rule.why || 'see its typography.json'}). Remove typography.hand.`);
  if (!rule.fonts.includes(id)) throw new Error(`${brand.id}/brand.json: hand face "${id}" is not allowed in ${approach}. Allowed: ${rule.fonts.join(', ')}`);
  return { ...face, tierRules: lib.tiers[face.tier], style: rule };
}

const isSerif = (face) => /serif/i.test(face.style) && !/sans/i.test(face.style);
export function fontStack(face, kind) {
  if (kind === 'mono') return `"${face.family}", ui-monospace, "SFMono-Regular", Menlo, monospace`;
  return isSerif(face) ? `"${face.family}", Georgia, "Times New Roman", serif` : `"${face.family}", system-ui, -apple-system, "Segoe UI", sans-serif`;
}

/** Google Fonts CSS2 URL for a list of faces. */
export function googleFontsUrl(faces) {
  const byFamily = new Map();
  for (const f of faces) {
    const cur = byFamily.get(f.family) || { weights: new Set(), italic: false };
    f.weights.forEach((w) => cur.weights.add(w));
    cur.italic = cur.italic || !!f.italic;
    byFamily.set(f.family, cur);
  }
  const parts = [...byFamily].map(([family, { weights, italic }]) => {
    const ws = [...weights].sort((a, b) => a - b);
    const name = family.replace(/ /g, '+');
    return italic ? `family=${name}:ital,wght@${[...ws.map((w) => `0,${w}`), ...ws.map((w) => `1,${w}`)].join(';')}` : `family=${name}:wght@${ws.join(';')}`;
  });
  return `https://fonts.googleapis.com/css2?${parts.join('&')}&display=swap`;
}

/** Sizes in px for each step of the scale. */
export function typeScale(base, ratio, steps) {
  return Object.fromEntries(Object.entries(steps).map(([k, n]) => [k, Math.round(base * ratio ** n * 10) / 10]));
}

export function buildTypography({ dist, brand }) {
  const write = (p, data) => {
    const full = join(dist, p);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, data);
  };
  const lib = loadPairings();
  const cfg = brand.config.typography || {};
  const pairing = lib.pairings.find((p) => p.id === cfg.pairing);
  if (!pairing) throw new Error(`${brand.id}/brand.json: unknown typography pairing "${cfg.pairing}". Available: ${lib.pairings.map((p) => p.id).join(', ')}`);
  const ratio = cfg.scale || 1.25;
  const P = brand.config.prefix;
  const web = typeScale(lib.scale.baseWeb, ratio, lib.scale.steps);
  const poster = typeScale(lib.scale.basePoster, ratio, lib.scale.steps);
  const hand = handFace(brand);
  const url = googleFontsUrl([pairing.display, pairing.body, pairing.mono, ...(hand ? [hand] : [])]);
  const { display: D, body: B, mono: Mo } = pairing;

  const banner = `/* ${brand.config.name} typography: ${pairing.name}. Generated by foundations/typography/build.mjs; do not edit by hand. */\n`;
  let css = `${banner}@import url("${url}");\n\n:root {\n`;
  css += `  --${P}-font-display: ${fontStack(D)};\n  --${P}-font-body: ${fontStack(B)};\n  --${P}-font-mono: ${fontStack(Mo, 'mono')};\n`;
  css += `  --${P}-weight-display: ${D.weights[D.weights.length > 1 ? 1 : 0]};\n  --${P}-weight-body: ${B.weights[0]};\n  --${P}-weight-strong: ${B.weights[B.weights.length - 1]};\n`;
  if (hand) css += `  --${P}-font-hand: "${hand.family}", cursive;\n`;
  css += `  --${P}-leading-display: ${D.leading};\n  --${P}-leading-body: ${B.leading};\n  --${P}-tracking-display: ${D.tracking}em;\n`;
  for (const [k, px] of Object.entries(web)) css += `  --${P}-text-${k}: ${Math.round((px / 16) * 1000) / 1000}rem;\n`;
  css += `  /* Poster sizes (base ${lib.scale.basePoster}px at A3 width; scale with the artboard) */\n`;
  for (const [k, px] of Object.entries(poster)) css += `  --${P}-poster-${k}: ${px}px;\n`;
  css += '}\n\n';
  const heading = (cls, step) => `.${P}-${cls} { font-family: var(--${P}-font-display); font-weight: var(--${P}-weight-display); font-size: var(--${P}-text-${step}); line-height: var(--${P}-leading-display); letter-spacing: var(--${P}-tracking-display); text-wrap: balance; }\n`;
  css += heading('hero', 'hero') + heading('display', 'display') + heading('h1', 'h1') + heading('h2', 'h2');
  css += `.${P}-h3 { font-family: var(--${P}-font-body); font-weight: var(--${P}-weight-strong); font-size: var(--${P}-text-h3); line-height: 1.25; }\n`;
  css += `.${P}-lead { font-family: var(--${P}-font-body); font-size: var(--${P}-text-lead); line-height: 1.45; }\n`;
  css += `.${P}-body { font-family: var(--${P}-font-body); font-weight: var(--${P}-weight-body); font-size: var(--${P}-text-body); line-height: var(--${P}-leading-body); max-width: 68ch; }\n`;
  css += `.${P}-small { font-family: var(--${P}-font-body); font-size: var(--${P}-text-small); line-height: 1.45; }\n`;
  css += `.${P}-label { font-family: var(--${P}-font-mono); font-size: var(--${P}-text-caption); letter-spacing: 0.1em; text-transform: uppercase; }\n`;
  css += `.${P}-data { font-family: var(--${P}-font-mono); font-variant-numeric: tabular-nums; }\n`;
  if (hand) {
    const factor = hand.tier === 'read' ? 1.15 : hand.tier === 'glance' ? 1.25 : 3;
    css += `/* Handwritten accent: ${hand.family} (${hand.tierRules.label}, up to ${Math.min(hand.tierRules.maxWords, hand.style.maxWords || 99)} words, one per piece). Never for body, prices, data, steps or buttons. */\n`;
    css += `.${P}-hand { font-family: var(--${P}-font-hand); font-weight: ${hand.weights[0]}; font-size: calc(var(--${P}-text-body) * ${factor}); line-height: 1.2; letter-spacing: 0; text-transform: none; }\n`;
  }
  write('web/css/typography.css', css);

  write('tokens/typography.json', JSON.stringify({ pairing, hand, ratio, sizes: { web, poster }, googleFontsUrl: url, rules: lib.rules }, null, 2) + '\n');

  let txt = `${brand.config.name}: ${pairing.name}\n\nInstall these free fonts (SIL Open Font License) for Figma, Adobe and Canva:\n\n`;
  for (const [role, f] of [['Headlines', D], ['Body', B], ['Data, dates, labels', Mo]]) {
    txt += `  ${role.padEnd(20)} ${f.family} (${f.weights.join(', ')}${f.italic ? ', italic' : ''})\n  ${''.padEnd(20)} https://fonts.google.com/specimen/${f.family.replace(/ /g, '+')}\n\n`;
  }
  if (hand) txt += `  ${'Handwritten accent'.padEnd(20)} ${hand.family} (${hand.weights.join(', ')}; ${hand.license}; ${hand.tierRules.label.toLowerCase()}, up to ${Math.min(hand.tierRules.maxWords, hand.style.maxWords || 99)} words, one per piece)\n  ${''.padEnd(20)} https://fonts.google.com/specimen/${hand.family.replace(/ /g, '+')}\n\n`;
  txt += `Type scale (ratio ${ratio}):\n`;
  for (const k of Object.keys(web)) txt += `  ${k.padEnd(9)} web ${String(web[k]).padStart(6)} px   poster ${String(poster[k]).padStart(6)} px\n`;
  txt += `\nRules:\n${lib.rules.map((r) => `  - ${r}`).join('\n')}\n`;
  write('design-apps/fonts.txt', txt);

  return [`typography: ${pairing.name} (${D.family} + ${B.family}${hand ? `, hand ${hand.family}` : ''}), scale ${ratio}`];
}
