// Messaging foundation: builds the playbook data, the browser copy checker and
// a readable message sheet from source/ and a brand's messaging.json.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadMessaging } from './context.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));

export function buildMessaging({ root, dist, brand }) {
  const write = (p, data) => {
    const full = join(dist, p);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, data);
  };
  const { principles, formats, words, message, ctx } = loadMessaging(root, brand);
  const clean = (o) => JSON.parse(JSON.stringify(o, (k, v) => (k.startsWith('$') ? undefined : v)));
  const msg = clean(message);

  const banner = `/* ${brand.config.name} messaging (UnDesigned). Generated by foundations/messaging/build.mjs; do not edit by hand. */\n`;

  // web: formats, rules and checkCopy() for templates and tools
  const lintSrc = readFileSync(join(HERE, 'lint.mjs'), 'utf8').replace(/^export /gm, '');
  write(
    'web/js/messaging.mjs',
    `${banner}${lintSrc}
const data = ${JSON.stringify({ principles: principles.principles, books: principles.books, stages: principles.stages, formats, message: msg })};
const ctx = ${JSON.stringify(ctx)};
const formats = ctx.formats;
const principles = Object.fromEntries(data.principles.map((p) => [p.id, p]));
const message = data.message;
/** Check one piece of copy against the playbook. Returns [{ level, check, principle, message }]. */
function check(piece) { return checkCopy(piece, ctx); }
export { data, formats, principles, message, check, checkCopy };
`,
  );

  // brand guide: readable message sheet
  let filled = 0;
  let total = 0;
  const v = (s) => {
    total++;
    if (Array.isArray(s) ? s.filter(Boolean).length : s) {
      filled++;
      return Array.isArray(s) ? s.filter(Boolean).join('; ') : s;
    }
    return '_to fill in_';
  };
  const bs = msg.brandscript;
  const ol = msg.oneLiner;
  let md = `<!-- Generated from products/${brand.id}/messaging.json by foundations/messaging/build.mjs. Edit the config, not this file. -->\n\n`;
  md += `# ${msg.brandName} message sheet\n\n`;
  md += `## One-liner\n\n${ol.problem || ol.solution || ol.result ? `${ol.problem} ${ol.solution} ${ol.result}`.trim() : '_to fill in_'}\n\n`;
  md += `| Problem | Solution | Result |\n|---|---|---|\n| ${v(ol.problem)} | ${v(ol.solution)} | ${v(ol.result)} |\n\n`;
  md += `## Positioning\n\n| | |\n|---|---|\n`;
  md += `| Who it's for | ${v(msg.positioning.audience)} |\n| In one sentence | ${v(msg.positioning.oneSentence)} |\n| In one paragraph | ${v(msg.positioning.oneParagraph)} |\n| Category | ${v(msg.positioning.category)} |\n| Different from | ${v(msg.positioning.differentFrom)} |\n\n`;
  md += `## BrandScript\n\n| Part | |\n|---|---|\n`;
  md += `| 1. Character | ${v(bs.character.who)} |\n| ... wants | ${v(bs.character.want)} |\n`;
  md += `| 2. Problem: villain | ${v(bs.problem.villain)} |\n| Problem: external | ${v(bs.problem.external)} |\n| Problem: internal | ${v(bs.problem.internal)} |\n| Problem: philosophical | ${v(bs.problem.philosophical)} |\n`;
  md += `| 3. Guide: empathy | ${v(bs.guide.empathy)} |\n| Guide: authority | ${v(bs.guide.authority)} |\n`;
  md += `| 4. Plan | ${v(bs.plan.steps)} |\n| Plan: promise | ${v(bs.plan.promise)} |\n`;
  md += `| 5. Call to action: direct | ${v(bs.callToAction.direct)} |\n| Call to action: transitional | ${v(bs.callToAction.transitional)} |\n`;
  md += `| 6. Failure (stakes) | ${v(bs.failure)} |\n| 7. Success | ${v(bs.success)} |\n`;
  md += `| Transformation | ${v(bs.transformation.from)} → ${v(bs.transformation.to)} |\n\n`;
  md += `## Voice\n\n| We are | We are not |\n|---|---|\n| ${v(msg.voice.is)} | ${v(msg.voice.isNot)} |\n\n`;
  md += `## Proof\n\n- Facts: ${v(msg.proof.facts)}\n- Testimonials: ${v(msg.proof.testimonials)}\n- Clients: ${v(msg.proof.clients)}\n\n`;
  md += `## Copy limits by format\n\nWords allowed per part (0 = leave it out).\n\n| Format | Headline | Subhead | Body | CTA | Notes |\n|---|---|---|---|---|---|\n`;
  for (const g of formats) for (const f of g.formats) {
    md += `| ${f.name} | ${f.limits.headline} | ${f.limits.subhead} | ${f.limits.body} | ${f.limits.cta} | ${f.notes} |\n`;
  }
  write('brand-guide/message-sheet.md', md);

  // tokens (with the fill count, which the brand hub shows)
  write(
    'tokens/messaging.json',
    JSON.stringify({ ...principles, $comment: undefined, formats, words, message: msg, fill: { filled, total } }, null, 2) + '\n',
  );

  const n = principles.principles.length;
  const fmt = Object.keys(ctx.formats).length;
  return [
    `messaging: ${n} principles from ${principles.books.length} books, ${fmt} formats in ${formats.length} groups`,
    `  products/${brand.id}/messaging.json: ${filled} of ${total} message fields filled in`,
  ];
}
