// Measures advance widths (in em) of printable ASCII and a few typographic characters for the fonts the
// launch pieces use, so design.mjs can wrap and align text without a browser. Run once (needs Playwright):
//   node products/plutto/campaigns/launch/measure-fonts.mjs   -> font-metrics.json
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { execSync } from 'node:child_process';

const HERE = dirname(fileURLToPath(import.meta.url));
const req = createRequire(import.meta.url);
const { chromium } = req(join(execSync('npm root -g').toString().trim(), 'playwright'));
const FACES = {
  serif: "400 100px 'Instrument Serif'",
  serifItalic: "italic 400 100px 'Instrument Serif'",
  sans: "400 100px 'Instrument Sans'",
  sansMedium: "500 100px 'Instrument Sans'",
  sansBold: "600 100px 'Instrument Sans'",
  mono: "400 100px 'IBM Plex Mono'",
  symbols: "400 100px 'Noto Sans Symbols'",
};
const CHARS = Array.from({ length: 95 }, (_, i) => String.fromCharCode(32 + i)).join('') + '’‘“”–—·°′″…→×';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage();
await page.setContent(`<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Instrument+Serif:ital@0;1&family=Instrument+Sans:wght@400;500;600&family=IBM+Plex+Mono&family=Noto+Sans+Symbols&display=swap">
<p style="font-family:'Instrument Serif'">a<i>a</i></p><p style="font-family:'Instrument Sans'">a<b>a</b><span style="font-weight:500">a</span></p><p style="font-family:'IBM Plex Mono'">a</p><p style="font-family:'Noto Sans Symbols'">♈</p>`);
await page.evaluate(async (faces) => { for (const f of Object.values(faces)) await document.fonts.load(f, 'Aa♈'); await document.fonts.ready; }, FACES);
const out = await page.evaluate(({ faces, chars }) => {
  const c = document.createElement('canvas').getContext('2d');
  const res = {};
  for (const [k, f] of Object.entries(faces)) {
    c.font = f;
    const adv = {};
    for (const ch of chars) adv[ch] = +(c.measureText(ch).width / 100).toFixed(4);
    const H = c.measureText('H'), x = c.measureText('x');
    res[k] = { capHeight: +(H.actualBoundingBoxAscent / 100).toFixed(4), xHeight: +(x.actualBoundingBoxAscent / 100).toFixed(4), adv };
  }
  return res;
}, { faces: FACES, chars: CHARS });
writeFileSync(join(HERE, 'font-metrics.json'), JSON.stringify({ $comment: 'Generated by measure-fonts.mjs in Chromium. Advance widths and heights in em.', ...out }, null, 0) + '\n');
console.log(Object.fromEntries(Object.entries(out).map(([k, v]) => [k, [v.capHeight, v.xHeight, v.adv.a]])));
await browser.close();
