// Approaches: builds a brand's chosen design approach (brand.json -> approach):
// its data (approach, art, motion, typography), illustration library, motion CSS
// and example SVGs. Runs after the colour
// foundation, whose tokens give the palettes. Each approach lives in approaches/<id>/
// with approach.json, illustration.mjs, README.md and references/.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as humanistMinimal from './humanist-minimal/illustration.mjs';

// Register new approaches here: id -> engine module (createIllustrator, springEasing).
export const APPROACHES = { 'humanist-minimal': humanistMinimal };

const HERE = dirname(fileURLToPath(import.meta.url));
const DATA_FILES = ['art', 'motion', 'typography'];

/** Loads an approach: approach.json merged with art.json, motion.json and typography.json. */
export function loadApproach(id) {
  const dir = join(HERE, id);
  const read = (f) => JSON.parse(readFileSync(join(dir, f), 'utf8'));
  const strip = (o) => JSON.parse(JSON.stringify(o, (k, v) => (k === '$comment' ? undefined : v)));
  const approach = { id, ...strip(read('approach.json')) };
  for (const f of DATA_FILES) if (existsSync(join(dir, `${f}.json`))) approach[f] = strip(read(`${f}.json`));
  return approach;
}

/** Illustration palette for a combination's roles: ground and accent from Wada, ink Black, paper White. */
export function illustrationPalette(roles, byHex) {
  return { ground: byHex(roles.bg), accent: byHex(roles.accent), ink: byHex('black'), paper: byHex('white') };
}

export function buildApproach({ dist, brand }) {
  const id = brand.config.approach;
  const engine = APPROACHES[id];
  if (!engine) throw new Error(`products/${brand.id}/brand.json: unknown approach "${id}". Available: ${Object.keys(APPROACHES).join(', ')}`);
  const P = brand.config.prefix;
  const write = (p, data) => {
    const full = join(dist, p);
    mkdirSync(dirname(full), { recursive: true });
    writeFileSync(full, data);
  };
  const approach = loadApproach(id);
  const color = JSON.parse(readFileSync(join(dist, 'tokens/colors.json'), 'utf8'));
  const hexOf = Object.fromEntries(color.colors.map((c) => [c.id, c.hex]));
  const hex = (h) => hexOf[h];

  const primaryPalette = color.brand.find((b) => b.name === 'primary') || color.brand[0];
  const palettes = Object.fromEntries(color.brand.map((b) => [b.name, illustrationPalette(b.roles, hex)]));
  const primary = primaryPalette ? palettes[primaryPalette.name] : { ground: hex('white'), accent: hex('black'), ink: hex('black'), paper: hex('white') };

  const ill = engine.createIllustrator(approach, primary);
  const springs = Object.fromEntries(Object.entries(approach.motion.springs).map(([k, s]) => [k, engine.springEasing(s)]));
  const banner = `/* ${brand.config.name}: ${approach.name} approach (UnDesigned). Generated by approaches/build.mjs; do not edit by hand. */\n`;

  // tokens (springs resolved to CSS easings)
  write('tokens/approach.json', JSON.stringify({ ...approach, springsCss: springs, palettes }, null, 2) + '\n');

  // web: illustration library with the approach data and brand palettes built in
  const lib = readFileSync(join(HERE, id, 'illustration.mjs'), 'utf8').replace(/^export /gm, '');
  const combos = Object.fromEntries(color.combinations.map((c) => [c.id, { light: c.roles.light, dark: c.roles.dark }]));
  write(
    'web/js/illustration.mjs',
    `${banner}${lib}
const approach = ${JSON.stringify(approach)};
const palettes = ${JSON.stringify(palettes)};
const hexOf = ${JSON.stringify(hexOf)};
const combos = ${JSON.stringify(combos)};
/** Illustration palette for any Wada combination (1-348). */
function paletteFor(n, mode = 'light') {
  const r = combos[n] && combos[n][mode === 'dark' ? 'dark' : 'light'];
  if (!r) throw new Error('Unknown combination ' + n);
  return { ground: hexOf[r.bg], accent: hexOf[r.accent], ink: hexOf.black, paper: hexOf.white };
}
const illustrator = createIllustrator(approach, palettes.primary || Object.values(palettes)[0]);
/** scene({ motif, palette, animate }) -> SVG string. motifs: ${ill.motifs.join(', ')} */
const scene = illustrator.scene;
export { approach, palettes, paletteFor, illustrator, scene, createIllustrator, springEasing };
`,
  );

  // web: motion tokens and classes for any HTML element, plus corner radii
  const M = approach.motion;
  const mv = M.moves;
  const corners = approach.art.corners.scale;
  let css = `${banner}
/* Springs are simulated into linear() easings; the cubic-bezier lines before them are fallbacks for older browsers. */
:root {
${Object.entries(springs).map(([k, s]) => `  --ud-spring-${k}: ${s.easing};\n  --ud-spring-${k}-duration: ${s.duration}ms;`).join('\n')}
${Object.entries(M.easings).map(([k, e]) => `  --ud-ease-${k}: ${e.css};`).join('\n')}
  --ud-motion-draw: ${mv.draw.duration}ms;
  --ud-motion-morph: ${mv.morph.duration}ms;
  --ud-motion-breathe: ${mv.breathe.duration}ms;
  --ud-motion-float: ${mv.float.duration}ms;
  --ud-motion-stagger: ${M.choreography.stagger}ms;
  --ud-motion-hold: ${M.choreography.hold}ms;
${Object.entries(corners).map(([k, v]) => `  --ud-radius-${k}: ${v}px;`).join('\n')}
}

/* Line draws itself on. Put pathLength="1" on the SVG path. */
.ud-draw { stroke-dasharray: 1; stroke-dashoffset: 1; animation: ud-draw var(--ud-motion-draw) var(--ud-ease-draw) both; }
@keyframes ud-draw { to { stroke-dashoffset: 0; } }

/* Shape or element pops in on the lively spring (small overshoot). */
.ud-pop { transform-box: fill-box; transform-origin: center; animation: ud-pop var(--ud-spring-lively-duration) cubic-bezier(0.34, 1.56, 0.64, 1) both; animation-timing-function: var(--ud-spring-lively); }
@keyframes ud-pop { from { transform: scale(0); } to { transform: scale(1); } }

/* Text or block rises in on the gentle spring (after the art). */
.ud-rise { animation: ud-rise var(--ud-spring-gentle-duration) cubic-bezier(0.22, 1, 0.36, 1) both; animation-timing-function: var(--ud-spring-gentle); }
@keyframes ud-rise { from { transform: translateY(0.4em); opacity: 0; } to { transform: none; opacity: 1; } }

/* Resting life: breathe (scale) and float (drift). One per piece. */
.ud-breathe { transform-box: fill-box; transform-origin: center; animation: ud-breathe var(--ud-motion-breathe) var(--ud-ease-breathe) infinite alternate; }
@keyframes ud-breathe { from { transform: scale(${mv.breathe.scale[0]}); } to { transform: scale(${mv.breathe.scale[1]}); } }
.ud-float { animation: ud-float var(--ud-motion-float) var(--ud-ease-breathe) infinite alternate; }
@keyframes ud-float { from { transform: translateY(0); } to { transform: translateY(-${mv.float.distancePct}%); } }

/* Spring transitions for interactive UI (hover, open, toggle). */
.ud-spring { transition-property: transform, opacity, background-color, border-radius; transition-duration: var(--ud-spring-soft-duration); transition-timing-function: var(--ud-spring-soft); }

/* Stagger children: style="--i: 0", "--i: 1" ... */
.ud-stagger > * { animation-delay: calc(var(--i, 0) * var(--ud-motion-stagger)); }

@media (prefers-reduced-motion: reduce) {
  .ud-draw, .ud-pop, .ud-rise, .ud-breathe, .ud-float { animation: none; stroke-dashoffset: 0; }
  .ud-spring { transition: none; }
}
`;
  write('web/css/motion.css', css.replace(/--ud-/g, `--${P}-`).replace(/\.ud-/g, `.${P}-`).replace(/@keyframes ud-/g, `@keyframes ${P}-`).replace(/animation: ud-/g, `animation: ${P}-`));

  // example SVGs in the primary palette
  for (const motif of ill.motifs) {
    write(`illustration/svg/${motif}.svg`, ill.scene({ motif, animate: false, uid: motif.replace(/-/g, '') }) + '\n');
    write(`illustration/svg/${motif}-animated.svg`, ill.scene({ motif, animate: true, uid: motif.replace(/-/g, '') }) + '\n');
  }

  return [
    `approach: ${approach.name}, ${approach.principles.length} principles, ${approach.layers.length} layer rules, ${ill.motifs.length} motifs, ${Object.keys(springs).length} springs (${Object.entries(springs).map(([k, s]) => `${k} ${s.duration}ms`).join(', ')})`,
    `  illustrations use palette "${primaryPalette ? primaryPalette.name : 'none'}" (combination ${primaryPalette ? primaryPalette.combination : '-'})`,
  ];
}
